"use strict";

(function initializeReleaseData(global) {
    const release = global.PCShopRelease = global.PCShopRelease || {};

    release.version = "1.1.6";
    release.saveSchema = 3;
    release.owner = "cixanla";
    release.copyright = "Copyright © 2026 cixanla. All rights reserved.";

    release.locales = {
        tr: {
            serviceCenter: "Servis Merkezi",
            serviceCenterDescription: "Tamir işlerini, kurumsal ihaleleri ve müşteri memnuniyetini yönet.",
            brandMarket: "Marka ve Pazar",
            brandMarketDescription: "Kampanyaları, piyasa döngülerini ve rakip baskısını yönet.",
            intelligence: "İş Zekâsı",
            intelligenceDescription: "Finans geçmişini, tahminleri, verimliliği ve işletme riskini izle.",
            career: "Kariyer",
            careerDescription: "Günlük hedefleri, başarımları ve mağaza kilometre taşlarını tamamla.",
            openJobs: "Açık Servis İşleri",
            serviceHistory: "Tamamlanan İşler",
            corporateTenders: "Kurumsal İhaleler",
            noServiceJobs: "Şu anda bekleyen servis işi yok.",
            noTenders: "Şu anda açık kurumsal ihale yok.",
            repair: "Onar",
            standardRepair: "Standart Onarım",
            premiumRepair: "Premium Onarım",
            partsCost: "Parça ve sarf maliyeti",
            expectedPayment: "Beklenen ödeme",
            successChance: "Başarı olasılığı",
            deadline: "Son gün",
            days: "gün",
            serviceCompleted: "Servis işi başarıyla tamamlandı.",
            serviceFailed: "Onarım başarısız oldu; müşteri ücret ödemedi.",
            technicianRequired: "Teknisyen enerjisi yetersiz. Çalışanı dinlendir veya premium servis kullan.",
            technician: "Teknisyen",
            ownerManaged: "Sahip yönetimi",
            activeJobs: "aktif iş",
            bulkSystemDeliveries: "Toplu sistem teslimatları",
            deliverTender: "İhaleyi Teslim Et",
            tenderDelivered: "Kurumsal ihale teslim edildi.",
            eligibleComputers: "Uygun bilgisayar",
            requiredScore: "Asgari sistem puanı",
            quantity: "Adet",
            reward: "Ödül",
            serviceQuality: "Servis Kalitesi",
            customerLoyalty: "Müşteri Sadakati",
            warrantyRisk: "Garanti Riski",
            activeCampaign: "Aktif Kampanya",
            campaigns: "Kampanyalar",
            startCampaign: "Kampanyayı Başlat",
            campaignRunning: "Kampanya devam ediyor",
            campaignStarted: "Pazarlama kampanyası başlatıldı.",
            campaignFinished: "Pazarlama kampanyası tamamlandı.",
            awareness: "Marka Bilinirliği",
            marketCycle: "Piyasa Döngüsü",
            competitorPressure: "Rakip Baskısı",
            trafficBonus: "Günlük müşteri artışı",
            campaignDuration: "Süre",
            campaignCost: "Bütçe",
            noActiveCampaign: "Aktif kampanya yok",
            serviceDeliveries: "servis teslimatı",
            campaignsDescription: "Her kampanya farklı müşteri akışı ve marka etkisi üretir.",
            supplierRelations: "Tedarikçi İlişkileri",
            supplierRelationsDescription: "Güven yükseldikçe fiyat indirimi kazanırsın; anlaşma seçili tedarikçide ek %8 sağlar.",
            orders: "sipariş",
            supplierDeal: "Anlaşma",
            supplierDealActivity: "5 günlük tedarik anlaşması (%8).",
            changesIn: "Değişime",
            economyPulse: "Ekonomi Nabzı",
            demand: "Talep",
            priceIndex: "Fiyat endeksi",
            stockIndex: "Stok endeksi",
            financialHistory: "Finans Geçmişi",
            cashForecast: "7 Günlük Kasa Tahmini",
            businessHealth: "İşletme Sağlığı",
            riskScore: "Risk Skoru",
            profitMargin: "Kâr Marjı",
            inventoryTurnover: "Stok Devir Hızı",
            averageStaffEnergy: "Ortalama Personel Enerjisi",
            noHistory: "İlk gün tamamlandığında finans grafikleri burada oluşacak.",
            revenue: "Gelir",
            expense: "Gider",
            profit: "Net Sonuç",
            cash: "Kasa",
            lastSevenDays: "Son 7 iş günü",
            perDay: "günlük ortalama",
            operationalEfficiency: "Operasyon Verimliliği",
            transactionLedger: "İşlem Defteri",
            ledgerDescription: "Son 500 işlem yerel kayıt dosyasında tutulur.",
            dailyObjectives: "Günlük Hedefler",
            achievements: "Başarımlar",
            milestones: "Kilometre Taşları",
            claimReward: "Ödülü Al",
            objectiveCompleted: "Hedef tamamlandı",
            objectiveRewarded: "Hedef ödülü kasaya aktarıldı.",
            achievementUnlocked: "Başarım açıldı",
            completed: "Tamamlandı",
            inProgress: "Devam ediyor",
            locked: "Kilitli",
            levelLabel: "Seviye",
            daysCompletedLabel: "Tamamlanan gün",
            lifetimeRevenueLabel: "Toplam gelir",
            reputationLabel: "İtibar",
            objectivesDescription: "Her iş gününde değişen üç operasyon hedefi.",
            ownerSignature: "Geliştiren ve yayımlayan",
            allRightsReserved: "Tüm hakları saklıdır.",
            releaseBuild: "Kararlı sürüm",
            settingsTitle: "Oyun Ayarları",
            settingsSubtitle: "Görüntü, ses, oynanış, erişilebilirlik ve veri tercihleri",
            general: "Genel",
            display: "Görüntü",
            audio: "Ses",
            gameplay: "Oynanış",
            accessibility: "Erişilebilirlik",
            controls: "Kontroller",
            data: "Veri",
            about: "Hakkında",
            language: "Dil",
            autoSave: "Otomatik kayıt",
            autoSaveDescription: "Oyun ilerlemesini belirli aralıklarla güvenli biçimde kaydeder.",
            saveInterval: "Kayıt aralığı",
            secondsShort: "sn",
            pauseOnBlur: "Odak kaybolunca duraklat",
            pauseOnBlurDescription: "Başka pencereye geçtiğinde oyun saatini otomatik durdurur.",
            notifications: "Bildirimler",
            fullscreen: "Tam ekran",
            fullscreenDescription: "Oyunu ekranın tamamında çalıştırır. F11 ile de değiştirilebilir.",
            displayDescription: "Arayüz tercihleri anında uygulanır ve yeniden başlatmada korunur.",
            uiScale: "Arayüz ölçeği",
            visualQuality: "Görsel kalite",
            qualityLow: "Performans",
            qualityHigh: "Yüksek",
            masterVolume: "Ana ses",
            interfaceVolume: "Arayüz sesleri",
            muteInBackground: "Arka planda sessize al",
            audioDescription: "Arayüz sesleri uygulama içinde düşük gecikmeyle üretilir.",
            testSound: "Ses Testi",
            difficulty: "Ekonomi zorluğu",
            difficultyRelaxed: "Rahat",
            difficultyNormal: "Normal",
            difficultyExpert: "Uzman",
            eventFrequency: "Olay sıklığı",
            frequencyLow: "Düşük",
            frequencyNormal: "Normal",
            frequencyHigh: "Yüksek",
            tutorialHints: "Yönlendirici ipuçları",
            gameplayDescription: "Zorluk; müşterileri, servis başarısını, giderleri ve pazar fiyatlarını etkiler.",
            reduceMotion: "Hareketi azalt",
            highContrast: "Yüksek kontrast",
            largeText: "Büyük metin",
            colorProfile: "Renk profili",
            colorDefault: "Varsayılan",
            colorDeuteranopia: "Yeşil-kırmızı desteği",
            colorTritanopia: "Mavi-sarı desteği",
            largerTargets: "Büyük etkileşim alanları",
            accessibilityDescription: "Okunabilirlik, hareket ve renk desteğini kişiselleştir.",
            keyboardShortcuts: "Klavye Kısayolları",
            pauseKey: "Boşluk: Duraklat / Devam",
            speedKeys: "1, 2, 4: Oyun hızı",
            navigationKeys: "Alt + 1…9: Ana ekranlar",
            fullscreenKey: "F11: Tam ekran",
            escapeKey: "Escape: Açık pencereyi kapat",
            activeSave: "Aktif kayıt yuvası",
            saveNow: "Şimdi Kaydet",
            exportSave: "Kaydı Dışa Aktar",
            importSave: "Kaydı İçe Aktar",
            resetSettings: "Ayarları Varsayılana Döndür",
            apply: "Uygula",
            close: "Kapat",
            reset: "Sıfırla",
            settingsApplied: "Ayarlar uygulandı.",
            saveExported: "Kayıt yedeği dışa aktarıldı.",
            saveImported: "Kayıt yedeği içe aktarıldı.",
            invalidSaveFile: "Bu dosya geçerli bir PC Shop Empire kaydı değil.",
            applicationInfo: "Uygulama Bilgisi",
            privacyLocal: "Kayıtlar bu bilgisayarda yerel olarak saklanır.",
            thirdPartyNotice: "Electron ve Chromium bileşenleri kendi açık kaynak lisanslarına tabidir.",
            settingsReset: "Ayarlar varsayılan değerlere döndürüldü.",
            calmMarket: "Dengeli Piyasa",
            supplySurplus: "Tedarik Bolluğu",
            componentShortage: "Parça Darboğazı",
            gamingSeason: "Oyun Sezonu",
            businessWave: "Kurumsal Talep Dalgası",
            priceWar: "Fiyat Rekabeti",
            marketDescriptionCalm: "Fiyat ve stoklar olağan seviyede.",
            marketDescriptionSurplus: "Tedarikçiler yüksek stokla indirim yapıyor.",
            marketDescriptionShortage: "Stok daraldı; bazı parçaların maliyeti yükseldi.",
            marketDescriptionGaming: "Oyuncu sistemlerine talep hızla artıyor.",
            marketDescriptionBusiness: "Şirketler toplu sistem alımı için pazara girdi.",
            marketDescriptionPriceWar: "Rakipler müşteri kazanmak için marjları düşürüyor.",
            lowRisk: "Düşük risk",
            mediumRisk: "Kontrollü risk",
            highRisk: "Yüksek risk",
            excellent: "Mükemmel",
            stable: "İstikrarlı",
            fragile: "Kırılgan",
            critical: "Kritik"
        },
        en: {
            serviceCenter: "Service Center", serviceCenterDescription: "Manage repairs, corporate tenders and customer satisfaction.",
            brandMarket: "Brand & Market", brandMarketDescription: "Manage campaigns, market cycles and competitive pressure.",
            intelligence: "Business Intelligence", intelligenceDescription: "Track financial history, forecasts, efficiency and business risk.",
            career: "Career", careerDescription: "Complete daily objectives, achievements and store milestones.",
            openJobs: "Open Service Jobs", serviceHistory: "Completed Jobs", corporateTenders: "Corporate Tenders",
            noServiceJobs: "There are no service jobs waiting.", noTenders: "There are no open corporate tenders.", repair: "Repair",
            standardRepair: "Standard Repair", premiumRepair: "Premium Repair", partsCost: "Parts and supplies", expectedPayment: "Expected payment",
            successChance: "Success chance", deadline: "Deadline", days: "days", serviceCompleted: "Service job completed successfully.",
            serviceFailed: "The repair failed; the customer was not charged.", technicianRequired: "Technician energy is insufficient. Rest the employee or use premium service.",
            technician: "Technician", ownerManaged: "Owner managed", activeJobs: "active jobs", bulkSystemDeliveries: "Bulk system deliveries",
            deliverTender: "Deliver Tender", tenderDelivered: "Corporate tender delivered.", eligibleComputers: "Eligible computers", requiredScore: "Minimum system score",
            quantity: "Quantity", reward: "Reward", serviceQuality: "Service Quality", customerLoyalty: "Customer Loyalty", warrantyRisk: "Warranty Risk",
            activeCampaign: "Active Campaign", campaigns: "Campaigns", startCampaign: "Start Campaign", campaignRunning: "Campaign in progress",
            campaignStarted: "Marketing campaign started.", campaignFinished: "Marketing campaign completed.", awareness: "Brand Awareness",
            marketCycle: "Market Cycle", competitorPressure: "Competitive Pressure", trafficBonus: "Daily customer increase", campaignDuration: "Duration", campaignCost: "Budget",
            noActiveCampaign: "No active campaign", serviceDeliveries: "service deliveries", campaignsDescription: "Each campaign creates a different customer flow and brand effect.",
            supplierRelations: "Supplier Relations", supplierRelationsDescription: "Higher trust unlocks discounts; a deal adds 8% savings with the selected supplier.", orders: "orders", supplierDeal: "Deal", supplierDealActivity: "5-day supply deal (8%).", changesIn: "Changes in",
            economyPulse: "Economy Pulse", demand: "Demand", priceIndex: "Price index", stockIndex: "Stock index",
            financialHistory: "Financial History", cashForecast: "7-Day Cash Forecast", businessHealth: "Business Health", riskScore: "Risk Score",
            profitMargin: "Profit Margin", inventoryTurnover: "Inventory Turnover", averageStaffEnergy: "Average Staff Energy",
            noHistory: "Financial charts will appear after the first completed day.", revenue: "Revenue", expense: "Expense", profit: "Net Result", cash: "Cash", lastSevenDays: "Last 7 working days",
            perDay: "daily average", operationalEfficiency: "Operational Efficiency", transactionLedger: "Transaction Ledger", ledgerDescription: "The latest 500 transactions are stored in the local save file.",
            dailyObjectives: "Daily Objectives", achievements: "Achievements", milestones: "Milestones", claimReward: "Claim Reward", objectiveCompleted: "Objective completed",
            objectiveRewarded: "Objective reward was added to cash.", achievementUnlocked: "Achievement unlocked", completed: "Completed", inProgress: "In progress", locked: "Locked",
            levelLabel: "Level", daysCompletedLabel: "Days completed", lifetimeRevenueLabel: "Lifetime revenue", reputationLabel: "Reputation", objectivesDescription: "Three operational objectives rotate each working day.",
            ownerSignature: "Developed and published by", allRightsReserved: "All rights reserved.", releaseBuild: "Stable release",
            settingsTitle: "Game Settings", settingsSubtitle: "Display, audio, gameplay, accessibility and data preferences", general: "General", display: "Display", audio: "Audio",
            gameplay: "Gameplay", accessibility: "Accessibility", controls: "Controls", data: "Data", about: "About", language: "Language",
            autoSave: "Auto save", autoSaveDescription: "Safely saves progress at regular intervals.", pauseOnBlur: "Pause when unfocused",
            saveInterval: "Save interval", secondsShort: "sec",
            pauseOnBlurDescription: "Automatically pauses the game clock when you switch windows.", notifications: "Notifications", fullscreen: "Fullscreen",
            fullscreenDescription: "Runs the game across the entire display. F11 also toggles it.", uiScale: "Interface scale", visualQuality: "Visual quality",
            displayDescription: "Interface preferences apply immediately and persist after restarting.",
            qualityLow: "Performance", qualityHigh: "High", masterVolume: "Master volume", interfaceVolume: "Interface sounds", muteInBackground: "Mute in background",
            audioDescription: "Interface sounds are generated inside the application with low latency.", testSound: "Test Sound",
            difficulty: "Economy difficulty", difficultyRelaxed: "Relaxed", difficultyNormal: "Normal", difficultyExpert: "Expert", eventFrequency: "Event frequency",
            frequencyLow: "Low", frequencyNormal: "Normal", frequencyHigh: "High", tutorialHints: "Guidance hints", gameplayDescription: "Difficulty affects customers, service success, expenses and market prices.", reduceMotion: "Reduce motion", highContrast: "High contrast",
            largeText: "Large text", colorProfile: "Color profile", colorDefault: "Default", colorDeuteranopia: "Red-green support", colorTritanopia: "Blue-yellow support",
            largerTargets: "Larger interaction targets", keyboardShortcuts: "Keyboard Shortcuts", pauseKey: "Space: Pause / resume", speedKeys: "1, 2, 4: Game speed",
            accessibilityDescription: "Customize readability, motion and color support.",
            navigationKeys: "Alt + 1…9: Main screens", fullscreenKey: "F11: Fullscreen", escapeKey: "Escape: Close open window", activeSave: "Active save slot",
            saveNow: "Save Now", exportSave: "Export Save", importSave: "Import Save", resetSettings: "Restore Default Settings", apply: "Apply", close: "Close", reset: "Reset",
            settingsApplied: "Settings applied.", saveExported: "Save backup exported.", saveImported: "Save backup imported.", invalidSaveFile: "This is not a valid PC Shop Empire save.",
            applicationInfo: "Application Information", privacyLocal: "Saves are stored locally on this computer.", thirdPartyNotice: "Electron and Chromium components remain subject to their open-source licenses.", settingsReset: "Settings restored to defaults.",
            calmMarket: "Balanced Market", supplySurplus: "Supply Surplus", componentShortage: "Component Shortage", gamingSeason: "Gaming Season",
            businessWave: "Corporate Demand Wave", priceWar: "Price Competition", marketDescriptionCalm: "Prices and stock are at normal levels.",
            marketDescriptionSurplus: "Suppliers are discounting abundant inventory.", marketDescriptionShortage: "Supply is tight and some component costs increased.",
            marketDescriptionGaming: "Demand for gaming systems is accelerating.", marketDescriptionBusiness: "Companies entered the market for bulk systems.",
            marketDescriptionPriceWar: "Competitors are cutting margins to win customers.", lowRisk: "Low risk", mediumRisk: "Controlled risk", highRisk: "High risk",
            excellent: "Excellent", stable: "Stable", fragile: "Fragile", critical: "Critical"
        },
        de: {
            serviceCenter: "Servicezentrum", serviceCenterDescription: "Verwalte Reparaturen, Firmenaufträge und Kundenzufriedenheit.",
            brandMarket: "Marke & Markt", brandMarketDescription: "Verwalte Kampagnen, Marktzyklen und Wettbewerbsdruck.",
            intelligence: "Geschäftsanalyse", intelligenceDescription: "Beobachte Finanzverlauf, Prognosen, Effizienz und Geschäftsrisiken.",
            career: "Karriere", careerDescription: "Erfülle Tagesziele, Erfolge und Meilensteine.",
            openJobs: "Offene Serviceaufträge", serviceHistory: "Abgeschlossene Aufträge", corporateTenders: "Firmenausschreibungen",
            noServiceJobs: "Derzeit warten keine Serviceaufträge.", noTenders: "Derzeit gibt es keine offenen Ausschreibungen.", repair: "Reparieren",
            standardRepair: "Standardreparatur", premiumRepair: "Premiumreparatur", partsCost: "Teile und Material", expectedPayment: "Erwartete Zahlung",
            successChance: "Erfolgschance", deadline: "Frist", days: "Tage", serviceCompleted: "Serviceauftrag erfolgreich abgeschlossen.",
            serviceFailed: "Die Reparatur ist fehlgeschlagen; der Kunde zahlt nicht.", technicianRequired: "Technikerenergie ist zu niedrig. Mitarbeiter ausruhen oder Premiumservice nutzen.",
            technician: "Techniker", ownerManaged: "Vom Inhaber geführt", activeJobs: "aktive Aufträge", bulkSystemDeliveries: "Systemlieferungen in großer Stückzahl",
            deliverTender: "Auftrag liefern", tenderDelivered: "Firmenauftrag wurde geliefert.", eligibleComputers: "Geeignete Computer", requiredScore: "Mindestpunktzahl",
            quantity: "Menge", reward: "Belohnung", serviceQuality: "Servicequalität", customerLoyalty: "Kundentreue", warrantyRisk: "Garantierisiko",
            activeCampaign: "Aktive Kampagne", campaigns: "Kampagnen", startCampaign: "Kampagne starten", campaignRunning: "Kampagne läuft",
            campaignStarted: "Marketingkampagne gestartet.", campaignFinished: "Marketingkampagne abgeschlossen.", awareness: "Markenbekanntheit",
            marketCycle: "Marktzyklus", competitorPressure: "Wettbewerbsdruck", trafficBonus: "Zusätzliche Kunden pro Tag", campaignDuration: "Dauer", campaignCost: "Budget",
            noActiveCampaign: "Keine aktive Kampagne", serviceDeliveries: "Serviceauslieferungen", campaignsDescription: "Jede Kampagne erzeugt einen anderen Kundenstrom und Markeneffekt.",
            supplierRelations: "Lieferantenbeziehungen", supplierRelationsDescription: "Mehr Vertrauen schaltet Rabatte frei; ein Vertrag spart beim gewählten Lieferanten zusätzlich 8 %.", orders: "Bestellungen", supplierDeal: "Vertrag", supplierDealActivity: "5-tägiger Liefervertrag (8 %).", changesIn: "Wechsel in",
            economyPulse: "Wirtschaftslage", demand: "Nachfrage", priceIndex: "Preisindex", stockIndex: "Bestandsindex",
            financialHistory: "Finanzverlauf", cashForecast: "7-Tage-Kassenprognose", businessHealth: "Geschäftslage", riskScore: "Risikowert",
            profitMargin: "Gewinnmarge", inventoryTurnover: "Lagerumschlag", averageStaffEnergy: "Ø Mitarbeiterenergie",
            noHistory: "Finanzdiagramme erscheinen nach dem ersten abgeschlossenen Tag.", revenue: "Einnahmen", expense: "Ausgaben", profit: "Nettoergebnis", cash: "Kasse", lastSevenDays: "Letzte 7 Arbeitstage",
            perDay: "Tagesdurchschnitt", operationalEfficiency: "Betriebseffizienz", transactionLedger: "Transaktionsbuch", ledgerDescription: "Die letzten 500 Transaktionen werden im lokalen Spielstand gespeichert.",
            dailyObjectives: "Tagesziele", achievements: "Erfolge", milestones: "Meilensteine", claimReward: "Belohnung holen", objectiveCompleted: "Ziel erfüllt",
            objectiveRewarded: "Zielbelohnung wurde der Kasse gutgeschrieben.", achievementUnlocked: "Erfolg freigeschaltet", completed: "Abgeschlossen", inProgress: "In Arbeit", locked: "Gesperrt",
            levelLabel: "Stufe", daysCompletedLabel: "Abgeschlossene Tage", lifetimeRevenueLabel: "Gesamtumsatz", reputationLabel: "Ruf", objectivesDescription: "An jedem Arbeitstag wechseln drei operative Ziele.",
            ownerSignature: "Entwickelt und veröffentlicht von", allRightsReserved: "Alle Rechte vorbehalten.", releaseBuild: "Stabile Version",
            settingsTitle: "Spieleinstellungen", settingsSubtitle: "Anzeige, Audio, Spielablauf, Barrierefreiheit und Daten", general: "Allgemein", display: "Anzeige", audio: "Audio",
            gameplay: "Spielablauf", accessibility: "Barrierefreiheit", controls: "Steuerung", data: "Daten", about: "Über", language: "Sprache",
            autoSave: "Automatisch speichern", autoSaveDescription: "Speichert den Fortschritt regelmäßig und sicher.", pauseOnBlur: "Bei Fokusverlust pausieren",
            saveInterval: "Speicherintervall", secondsShort: "Sek.",
            pauseOnBlurDescription: "Pausiert die Spielzeit beim Wechsel zu einem anderen Fenster.", notifications: "Benachrichtigungen", fullscreen: "Vollbild",
            fullscreenDescription: "Zeigt das Spiel auf dem gesamten Bildschirm. F11 schaltet ebenfalls um.", uiScale: "Oberflächenskalierung", visualQuality: "Grafikqualität",
            displayDescription: "Oberflächeneinstellungen werden sofort angewendet und nach einem Neustart beibehalten.",
            qualityLow: "Leistung", qualityHigh: "Hoch", masterVolume: "Gesamtlautstärke", interfaceVolume: "Oberflächentöne", muteInBackground: "Im Hintergrund stumm",
            audioDescription: "Oberflächentöne werden mit geringer Verzögerung in der Anwendung erzeugt.", testSound: "Ton testen",
            difficulty: "Wirtschaftsschwierigkeit", difficultyRelaxed: "Entspannt", difficultyNormal: "Normal", difficultyExpert: "Experte", eventFrequency: "Ereignishäufigkeit",
            frequencyLow: "Niedrig", frequencyNormal: "Normal", frequencyHigh: "Hoch", tutorialHints: "Hinweise", gameplayDescription: "Der Schwierigkeitsgrad beeinflusst Kunden, Serviceerfolg, Kosten und Marktpreise.", reduceMotion: "Bewegung reduzieren", highContrast: "Hoher Kontrast",
            largeText: "Großer Text", colorProfile: "Farbprofil", colorDefault: "Standard", colorDeuteranopia: "Rot-Grün-Unterstützung", colorTritanopia: "Blau-Gelb-Unterstützung",
            largerTargets: "Größere Interaktionsflächen", keyboardShortcuts: "Tastenkürzel", pauseKey: "Leertaste: Pause / Fortsetzen", speedKeys: "1, 2, 4: Spielgeschwindigkeit",
            accessibilityDescription: "Lesbarkeit, Bewegung und Farbunterstützung anpassen.",
            navigationKeys: "Alt + 1…9: Hauptseiten", fullscreenKey: "F11: Vollbild", escapeKey: "Escape: Fenster schließen", activeSave: "Aktiver Spielstand",
            saveNow: "Jetzt speichern", exportSave: "Spielstand exportieren", importSave: "Spielstand importieren", resetSettings: "Standardeinstellungen", apply: "Anwenden", close: "Schließen", reset: "Zurücksetzen",
            settingsApplied: "Einstellungen angewendet.", saveExported: "Spielstand exportiert.", saveImported: "Spielstand importiert.", invalidSaveFile: "Diese Datei ist kein gültiger PC Shop Empire-Spielstand.",
            applicationInfo: "Anwendungsinformationen", privacyLocal: "Spielstände werden lokal auf diesem Computer gespeichert.", thirdPartyNotice: "Electron- und Chromium-Komponenten unterliegen ihren Open-Source-Lizenzen.", settingsReset: "Einstellungen zurückgesetzt.",
            calmMarket: "Ausgeglichener Markt", supplySurplus: "Lieferüberschuss", componentShortage: "Teileengpass", gamingSeason: "Gaming-Saison",
            businessWave: "Firmen-Nachfragewelle", priceWar: "Preiswettbewerb", marketDescriptionCalm: "Preise und Lagerbestände sind normal.",
            marketDescriptionSurplus: "Lieferanten reduzieren reichlich vorhandene Ware.", marketDescriptionShortage: "Das Angebot ist knapp und einige Teile werden teurer.",
            marketDescriptionGaming: "Die Nachfrage nach Gaming-Systemen steigt.", marketDescriptionBusiness: "Unternehmen kaufen Systeme in größeren Mengen.",
            marketDescriptionPriceWar: "Wettbewerber senken Margen, um Kunden zu gewinnen.", lowRisk: "Niedriges Risiko", mediumRisk: "Kontrolliertes Risiko", highRisk: "Hohes Risiko",
            excellent: "Ausgezeichnet", stable: "Stabil", fragile: "Fragil", critical: "Kritisch"
        }
    };

    release.text = function text(key) {
        const language = typeof gameState !== "undefined" && gameState?.language
            ? gameState.language
            : (document.documentElement.lang || "en");
        return release.locales[language]?.[key]
            || release.locales.en[key]
            || key;
    };

    release.marketCycles = {
        calm: { name: "calmMarket", description: "marketDescriptionCalm", price: 1, stock: 1, traffic: 0, tender: 0 },
        surplus: { name: "supplySurplus", description: "marketDescriptionSurplus", price: 0.88, stock: 1.35, traffic: 1, tender: 0 },
        shortage: { name: "componentShortage", description: "marketDescriptionShortage", price: 1.18, stock: 0.72, traffic: -1, tender: 0 },
        gaming: { name: "gamingSeason", description: "marketDescriptionGaming", price: 1.06, stock: 0.92, traffic: 3, tender: 0.15 },
        business: { name: "businessWave", description: "marketDescriptionBusiness", price: 1.04, stock: 1, traffic: 1, tender: 0.35 },
        priceWar: { name: "priceWar", description: "marketDescriptionPriceWar", price: 0.94, stock: 1.12, traffic: 2, tender: 0.08 }
    };

    release.campaigns = [
        { id: "local", icon: "◎", cost: 420, duration: 3, traffic: 2, awareness: 4, loyalty: 1,
            names: { tr: "Yerel Arama Reklamları", en: "Local Search Ads", de: "Lokale Suchanzeigen" },
            descriptions: { tr: "Yakındaki müşterilere düşük riskli ve ölçülebilir reklam.", en: "Low-risk, measurable advertising to nearby customers.", de: "Messbare Werbung mit geringem Risiko für lokale Kunden." } },
        { id: "social", icon: "◇", cost: 950, duration: 4, traffic: 4, awareness: 8, loyalty: 2,
            names: { tr: "Sosyal Medya Lansmanı", en: "Social Media Launch", de: "Social-Media-Start" },
            descriptions: { tr: "Yeni sistemleri vitrine çıkarır; hızlı bilinirlik sağlar.", en: "Showcases new systems and builds awareness quickly.", de: "Präsentiert neue Systeme und steigert schnell die Bekanntheit." } },
        { id: "community", icon: "◉", cost: 1650, duration: 5, traffic: 5, awareness: 11, loyalty: 5,
            names: { tr: "Topluluk Etkinliği", en: "Community Event", de: "Community-Event" },
            descriptions: { tr: "Atölye günü ve canlı montaj gösterisiyle sadakat oluşturur.", en: "Builds loyalty through a workshop day and live assembly showcase.", de: "Stärkt die Treue mit Werkstatttag und Live-Montage." } },
        { id: "business", icon: "▰", cost: 2400, duration: 6, traffic: 3, awareness: 9, loyalty: 3, tenderBonus: 0.35,
            names: { tr: "Kurumsal Satış Ekibi", en: "Business Sales Drive", de: "Firmenvertrieb" },
            descriptions: { tr: "Şirket müşterileri ve yüksek bütçeli ihaleleri hedefler.", en: "Targets corporate clients and high-budget tenders.", de: "Zielt auf Firmenkunden und hochwertige Ausschreibungen." } }
    ];

    release.serviceTemplates = [
        { id: "diagnostic", icon: "⌁", cost: [35, 80], payment: [260, 430], difficulty: 0.25,
            names: { tr: "Donanım Arıza Teşhisi", en: "Hardware Diagnostics", de: "Hardwarediagnose" } },
        { id: "thermal", icon: "≈", cost: [70, 150], payment: [390, 680], difficulty: 0.38,
            names: { tr: "Isınma ve Soğutma Bakımı", en: "Thermal Service", de: "Kühlungswartung" } },
        { id: "upgrade", icon: "▲", cost: [160, 340], payment: [680, 1180], difficulty: 0.48,
            names: { tr: "Performans Yükseltmesi", en: "Performance Upgrade", de: "Leistungsupgrade" } },
        { id: "recovery", icon: "◫", cost: [45, 120], payment: [520, 920], difficulty: 0.58,
            names: { tr: "Veri Kurtarma ve Sistem Onarımı", en: "Data Recovery & System Repair", de: "Datenrettung & Systemreparatur" } },
        { id: "urgent", icon: "!", cost: [190, 380], payment: [900, 1550], difficulty: 0.68,
            names: { tr: "Acil İş İstasyonu Onarımı", en: "Urgent Workstation Repair", de: "Dringende Workstation-Reparatur" } }
    ];

    release.objectiveDefinitions = [
        { id: "revenue", target: 2500, reward: 350, source: state => state.daily.revenue,
            labels: { tr: "Bugün €2.500 gelir elde et", en: "Earn €2,500 today", de: "Heute 2.500 € Umsatz erzielen" } },
        { id: "build", target: 2, reward: 280, source: state => state.daily.computersBuilt,
            labels: { tr: "Bugün 2 bilgisayar monte et", en: "Build 2 computers today", de: "Heute 2 Computer montieren" } },
        { id: "sell", target: 2, reward: 320, source: state => state.daily.computersSold,
            labels: { tr: "Bugün 2 bilgisayar teslim et", en: "Deliver 2 computers today", de: "Heute 2 Computer ausliefern" } },
        { id: "service", target: 2, reward: 300, source: state => state.daily.serviceJobs || 0,
            labels: { tr: "Bugün 2 servis işi tamamla", en: "Complete 2 service jobs today", de: "Heute 2 Serviceaufträge abschließen" } },
        { id: "profit", target: 1000, reward: 400, source: state => Math.max(0, state.daily.revenue - state.daily.expenses),
            labels: { tr: "Bugün €1.000 net fazlaya ulaş", en: "Reach €1,000 net surplus today", de: "Heute 1.000 € Nettoüberschuss erreichen" } },
        { id: "staff", target: 3, reward: 250, source: state => state.daily.staffTasks,
            labels: { tr: "Personelin 3 otomatik görev tamamlasın", en: "Have staff complete 3 automated tasks", de: "Mitarbeiter erledigen 3 automatische Aufgaben" } }
    ];

    release.achievementDefinitions = [
        { id: "first_sale", icon: "€", reward: 500, target: 1, source: state => state.lifetime.computersSold,
            names: { tr: "İlk Teslimat", en: "First Delivery", de: "Erste Lieferung" },
            descriptions: { tr: "İlk bilgisayar satışını tamamla.", en: "Complete your first computer sale.", de: "Schließe den ersten Computerverkauf ab." } },
        { id: "builder_25", icon: "⚒", reward: 1500, target: 25, source: state => state.lifetime.computersBuilt,
            names: { tr: "Usta Montajcı", en: "Master Builder", de: "Meisterbauer" },
            descriptions: { tr: "Toplam 25 bilgisayar monte et.", en: "Build 25 computers in total.", de: "Baue insgesamt 25 Computer." } },
        { id: "revenue_50k", icon: "◆", reward: 2500, target: 50000, source: state => state.lifetime.revenue,
            names: { tr: "Büyüyen İşletme", en: "Growing Business", de: "Wachsendes Geschäft" },
            descriptions: { tr: "Toplam €50.000 gelir elde et.", en: "Earn €50,000 lifetime revenue.", de: "Erziele insgesamt 50.000 € Umsatz." } },
        { id: "staff_5", icon: "♟", reward: 1800, target: 5, source: state => state.staff.length,
            names: { tr: "Gerçek Bir Ekip", en: "A Real Team", de: "Ein echtes Team" },
            descriptions: { tr: "Aynı anda 5 personel çalıştır.", en: "Employ 5 staff at once.", de: "Beschäftige gleichzeitig 5 Mitarbeiter." } },
        { id: "reputation_75", icon: "★", reward: 2200, target: 75, source: state => state.reputation,
            names: { tr: "Şehrin Güveni", en: "Trusted Across the City", de: "Vertrauen der Stadt" },
            descriptions: { tr: "75 itibara ulaş.", en: "Reach 75 reputation.", de: "Erreiche 75 Ruf." } },
        { id: "service_20", icon: "⌁", reward: 1700, target: 20, source: state => state.serviceCenter?.completed || 0,
            names: { tr: "Servis Uzmanı", en: "Service Specialist", de: "Servicespezialist" },
            descriptions: { tr: "20 servis işini başarıyla tamamla.", en: "Successfully complete 20 service jobs.", de: "Schließe 20 Serviceaufträge erfolgreich ab." } }
    ];
})(globalThis);
